INSERT INTO jewelry (name, type, color, price)
VALUES  ('Chain with pearls'    ,  'chain'   , 'silver',15),
        ('Cross bracelet'       ,  'bracelet', 'silver',7),
        ('Bow earrings'         ,  'earrings', 'white' ,10),
        ('Bow earrings'         ,  'earrings', 'pink'  ,10),
        ('Bow earrings'         ,  'earrings', 'black' ,10),
        ('Choker necklace'      ,  'chain'   , 'silver',45),
        ('Saturn necklace-cross',  'chain'   , 'silver',25),
        ('Saturn necklace-heart',  'chain'   , 'silver',25),
        ('Cross & thin chain'   ,  'chain'   , 'silver',15),
        ('Cross & thin chain'   ,  'chain'   , 'gold'  ,15),
        ('Cross & thick chain'  ,  'chain'   , 'silver',15),
        ('Cross & thick chain'  ,  'chain'   , 'silver',15),
        ('Clear sunglasses'     ,'sunglasses', 'silver',15),
        ('Necklaces & double cross & rhinestones', 'chain', 'silver',30),
        ('Necklaces & double cross & rhinestones', 'chain', 'gold'  ,30),
        ('Necklaces & rhinestones', 'chain'  , 'gold'  ,30),
        ('Necklaces & rhinestones', 'chain'  , 'silver',30),
        ('Two-side choker & thin chain', 'chain', 'silver',15);
